# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from model_template import model_pb2 as model__template_dot_model__pb2


class ModzyModelStub(object):
    """option java_package = "com.modzy.model.grpc";
    option java_multiple_files = true;

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/ModzyModel/Status',
                request_serializer=model__template_dot_model__pb2.StatusRequest.SerializeToString,
                response_deserializer=model__template_dot_model__pb2.StatusResponse.FromString,
                )
        self.RunBytes = channel.unary_unary(
                '/ModzyModel/RunBytes',
                request_serializer=model__template_dot_model__pb2.RunBytesRequest.SerializeToString,
                response_deserializer=model__template_dot_model__pb2.RunResponse.FromString,
                )
        self.RunStr = channel.unary_unary(
                '/ModzyModel/RunStr',
                request_serializer=model__template_dot_model__pb2.RunStrRequest.SerializeToString,
                response_deserializer=model__template_dot_model__pb2.RunResponse.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/ModzyModel/Shutdown',
                request_serializer=model__template_dot_model__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=model__template_dot_model__pb2.ShutdownResponse.FromString,
                )


class ModzyModelServicer(object):
    """option java_package = "com.modzy.model.grpc";
    option java_multiple_files = true;

    """

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModzyModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=model__template_dot_model__pb2.StatusRequest.FromString,
                    response_serializer=model__template_dot_model__pb2.StatusResponse.SerializeToString,
            ),
            'RunBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBytes,
                    request_deserializer=model__template_dot_model__pb2.RunBytesRequest.FromString,
                    response_serializer=model__template_dot_model__pb2.RunResponse.SerializeToString,
            ),
            'RunStr': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStr,
                    request_deserializer=model__template_dot_model__pb2.RunStrRequest.FromString,
                    response_serializer=model__template_dot_model__pb2.RunResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=model__template_dot_model__pb2.ShutdownRequest.FromString,
                    response_serializer=model__template_dot_model__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModzyModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModzyModel(object):
    """option java_package = "com.modzy.model.grpc";
    option java_multiple_files = true;

    """

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModzyModel/Status',
            model__template_dot_model__pb2.StatusRequest.SerializeToString,
            model__template_dot_model__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModzyModel/RunBytes',
            model__template_dot_model__pb2.RunBytesRequest.SerializeToString,
            model__template_dot_model__pb2.RunResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunStr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModzyModel/RunStr',
            model__template_dot_model__pb2.RunStrRequest.SerializeToString,
            model__template_dot_model__pb2.RunResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModzyModel/Shutdown',
            model__template_dot_model__pb2.ShutdownRequest.SerializeToString,
            model__template_dot_model__pb2.ShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
